import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { runBuild } from './helpers/run-build.js';
import { checkInstallSourceParity } from '../../shared/build-helpers/manifest-parity.js';

// Drift gate for this plugin's manifest catalog.
//
// The catalog is a path catalog (no sha256) so a rebuild + `git diff` gate (as
// used for the standard installer) can never detect when the installable
// payload and the catalog diverge. Instead we build the REAL runtime-config and
// documentation corpus into an isolated tmp output/ (adapter engine / lib build
// / UI all skipped — fast and race-free) and assert the staged _install-source/
// tree matches the catalog's sourcePath set in both directions. Add/rename/
// remove a template or action-event and forget the catalog → this fails.
//
// The comparison target is the BUILT catalog, not the committed one: the docs
// entries are generated by the build's merge-docs-manifest step and never land
// in the source tree. Reading the committed file here would leave every docs
// entry unchecked and would pass on a variant never wired for the corpus.

test('built _install-source/ matches the built manifest catalog', async () => {
  const { outRoot, cleanup } = await runBuild({ realRuntimeConfig: true });
  try {
    const manifestsDir = path.join(outRoot, 'manifests');
    const catalogs = fs.readdirSync(manifestsDir).filter((f) => /^v.+\.json$/.test(f));
    assert.equal(catalogs.length, 1,
      `expected exactly one built catalog under manifests/, found: ${catalogs.join(', ') || '(none)'}`);
    const manifest = JSON.parse(fs.readFileSync(path.join(manifestsDir, catalogs[0]), 'utf8'));
    const { missing, orphans } = checkInstallSourceParity({ outputDir: outRoot, manifest });
    assert.deepEqual(missing, [],
      `manifest lists sourcePath(s) with no built file (install would ENOENT): ${missing.join(', ')}`);
    assert.deepEqual(orphans, [],
      `built _install-source file(s) not listed in the manifest (would never install): ${orphans.join(', ')}`);
  } finally {
    cleanup();
  }
});
