import { strict as assert } from 'node:assert';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const repoRoot = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../..');
const SKIP_DIRS = new Set([
  'node_modules', '.git', '.next', 'dist', 'build', 'out', 'coverage', 'archive',
  // `.agents/` is the dev-only meta skills tree (non-production prompts and
  // skills) — its prose intentionally references current and historical skill
  // paths and is not policed by the production sweep.
  '.agents',
  // Historical iteration notes — frozen records of past refactors. Same
  // intent as `archive/`; these aren't active code and shouldn't be policed.
  '_private',
  // installer/src/ is gitignored and auto-regenerated by sync-source.js at
  // prepack time — any stale path strings there are local-only artifacts,
  // not active code. Mirrors the existing `installer` skip in test-prose-skill-refs.
  'installer',
]);
const SKIP_FILE_GLOBS = [
  // Historical baseline run-notes — intentionally frozen
  /[\\/]baseline-[^\\/]+[\\/]run-notes\.md$/,
  /[\\/]baseline-[^\\/]+[\\/]lint-report\.md$/,
  // Root README.md is not in the corrective's File Targets — out of scope.
  /^README\.md$/,
  // The sweep test itself contains the literal search string as a pattern,
  // not as a functional path. Exclude self-reference to avoid false positive.
  /[\\/]test-functional-path-sweep\.test\.mjs$/,
];
const SCAN_EXTS = new Set(['.md', '.js', '.ts', '.mjs', '.cjs', '.yml', '.yaml']);
function walk(dir, out=[]) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { walk(p, out); continue; }
    if (!SCAN_EXTS.has(path.extname(e.name))) continue;
    const rel = path.relative(repoRoot, p);
    if (SKIP_FILE_GLOBS.some(rx => rx.test(rel) || rx.test(p))) continue;
    out.push(p);
  }
  return out;
}
// Pre-rename skill folder names from PR #77 (RAD-SKILL-DISCOVERY). All have
// since been renamed to `rad-<name>`. The sweep flags any production code
// still referring to the pre-rename folder. Boundary chars (`/`, `'`, `"`)
// keep e.g. `skills/execute/` from matching `skills/execute-parallel/`.
const OLD_SKILL_NAMES = [
  'orchestration', 'brainstormer', 'code-review', 'create-plans',
  'execute', 'execute-coding-task', 'execute-parallel',
  'plan-audit', 'run-tests', 'source-control',
  'log-error', 'create-skill', 'configure-system',
];
const hits = [];
for (const f of walk(repoRoot)) {
  const text = readFileSync(f, 'utf8');
  const lines = text.split(/\r?\n/);
  lines.forEach((line, i) => {
    for (const name of OLD_SKILL_NAMES) {
      if (
        line.includes(`skills/${name}/`) ||
        line.includes(`'skills', '${name}'`) ||
        line.includes(`"skills", "${name}"`)
      ) {
        hits.push(`${path.relative(repoRoot, f)}:${i + 1}: ${line.trim().slice(0, 120)}`);
        break;
      }
    }
  });
}
assert.deepEqual(hits, [], 'functional pre-rename `skills/<name>/` path strings remain in active code:\n  - ' + hits.join('\n  - '));
console.log('functional path-string sweep assertions passed');
