import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const repoRoot = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../..');
const md = readFileSync(path.join(repoRoot, '.claude/agents/planner.md'), 'utf8');
assert.match(md, /^## Spawn Prompt Conventions\s*$/m, 'planner.md must carry an H2 `## Spawn Prompt Conventions` section');
assert.match(md, /## Repository Skills Available/, 'planner.md must reference the literal `## Repository Skills Available` heading');
assert.match(md, /catalog only|Catalog only/i, 'planner.md must clarify entries are catalog-only');
assert.match(md, /absent.*normal|Absent section is normal/i, 'planner.md must teach the absent-section-is-normal rule');
console.log('planner agent conventions assertions passed');
